# Generated by Django 4.0.2 on 2022-03-28 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(unique=True)),
                ('Article', models.TextField()),
                ('Author', models.TextField()),
                ('AuthorID', models.TextField()),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('LastUpdate', models.DateTimeField()),
                ('Visits', models.IntegerField()),
                ('Likes', models.IntegerField()),
                ('Dislikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleID', models.IntegerField()),
                ('Name', models.TextField()),
                ('Question', models.TextField()),
            ],
        ),
    ]
