# Generated by Django 4.0.2 on 2022-03-12 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0002_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
