# Generated by Django 4.0.2 on 2022-03-12 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0003_alter_statistics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
