# Generated by Django 4.0.2 on 2022-03-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0005_passedexams'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='Answer',
            field=models.TextField(default='ans'),
            preserve_default=False,
        ),
    ]
