# Generated by Django 4.0.2 on 2022-03-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0006_exams_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='Name',
            new_name='Answers',
        ),
    ]
