# Generated by Django 4.0.2 on 2022-03-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0007_rename_name_exams_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='Answers',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='Question',
        ),
    ]
