# Generated by Django 4.0.2 on 2022-03-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0008_remove_exams_answer_remove_exams_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='Answer',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exams',
            name='Answers',
            field=models.TextField(default='kak'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exams',
            name='Question',
            field=models.TextField(default='2'),
            preserve_default=False,
        ),
    ]
