# Generated by Django 4.0.2 on 2022-03-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0009_exams_answer_exams_answers_exams_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='Answer',
            new_name='CorrectAnswer',
        ),
    ]
