# Generated by Django 4.0.2 on 2022-04-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0010_rename_answer_exams_correctanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='What',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kak', models.IntegerField()),
            ],
        ),
    ]
