# Generated by Django 4.0.2 on 2022-04-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0011_what'),
    ]

    operations = [
        migrations.DeleteModel(
            name='What',
        ),
    ]
