# Generated by Django 4.0.2 on 2022-04-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0012_delete_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Name',
            field=models.TextField(),
        ),
    ]
