# Generated by Django 4.0.2 on 2022-04-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0014_alter_articles_lastupdate_alter_articles_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('ArticleID', models.IntegerField()),
                ('Like', models.BooleanField()),
            ],
        ),
    ]
