# Generated by Django 4.0.2 on 2022-04-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0016_passedexams_maxresult_passedexams_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedexams',
            name='Passed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
