# Generated by Django 4.0.2 on 2022-04-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialApp', '0017_passedexams_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('Purpose', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='statistics',
            name='CostCategory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='CostDescription',
            field=models.TextField(blank=True),
        ),
    ]
